default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: my-secret-password
  host: localhost  # ローカル環境では 'localhost' が使われる場合が多い
  port: 3306       # ローカルのMySQLコンテナのポート番号

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
